services:
  latex-api:
    build:
      dockerfile: Dockerfile.dev
    command: npm run dev
    volumes:
      - ./src:/app/src
      - /app/node_modules
      - /var/run/docker.sock:/var/run/docker.sock  # Permet à l'API d'exécuter Docker
    environment:
      - NODE_ENV=development
  
  # Ajout du service pour construire l'image latex-compiler
  latex-compiler:
    extends:
      file: docker-compose.yml
      service: latex-compiler