FROM node:23-slim

RUN apt-get update && \
    apt-get install -y \
    texlive-latex-recommended \
    texlive-latex-extra \
    texlive-fonts-recommended && \
    apt-get clean

# RUN apk update && apk add --no-cache \
#     texlive \
#     texmf-dist-latex \
#     texmf-dist-fontsrecommended \
#     texmf-dist-latexextra

WORKDIR /app

COPY package*.json ./
RUN npm install -g nodemon && npm install

COPY . .

EXPOSE 3000
CMD ["npm", "run", "dev"]
